/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(show_image.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bd77911a08c388a4b9dc803945c8873a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <display/show_image.h>
// pydoc.h is automatically generated in the build directory
#include <show_image_pydoc.h>

void bind_show_image(py::module& m)
{

    using show_image = ::gr::display::show_image;


    py::class_<show_image,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<show_image>>(m, "show_image", D(show_image))

        .def(py::init(&show_image::make),
             py::arg("imagewidth"),
             py::arg("imageheight"),
             py::arg("parent") = nullptr,
             D(show_image, make))


        .def("exec_", &show_image::exec_, D(show_image, exec_))


        .def(
            "qwidget",
            [](show_image& self) { return reinterpret_cast<uintptr_t>(self.qwidget()); },
            D(show_image, qwidget))


        .def("displayBottomUp",
             &show_image::displayBottomUp,
             py::arg("direction"),
             D(show_image, displayBottomUp))

        ;
}
